development:
  secret_key_base: 9bef33e63f6e5ba6a2cc09a4cd746a48fdc887d88dbf79e903d30b8ddc5e3906e70fd74db4834a1986e4ab6e1d282477f0d3aa8e3d7700debf96ad0d258c0b0c
  github_username: your-username-here
  github_password: your-password-here
  github_secret:   your-secret-here
test:
  secret_key_base: 3770861f9777fd5b312e6688720a1c14a4d32a27e3b4a8844acb0cb956b046f5abc5d3f57385e712229c4557312aaeebf359ae4fb6171a4f67e142a41d77a198
  github_username: your-username-here
  github_password: your-password-here
  github_secret:   your-secret-here
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_username: <%= ENV["GITHUB_USERNAME"] %>
  github_password: <%= ENV["GITHUB_PASSWORD"] %>
  github_secret:   <%= ENV["GITHUB_SECRET"] %>
